name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
          
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        echo "Inicia Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Termina Login"
        
    - name: Build Dokcer Image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker build --tag rpacheco26/docker-graphql:$NEW_VERSION .
        docker build --tag rpacheco26/docker-graphql:latest . 
        
    - name: Push Dokcer Image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker push rpacheco26/docker-graphql:$NEW_VERSION
        docker push rpacheco26/docker-graphql:latest
        
        
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
