name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Inicia Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Termina Login"
    - name: Build Dokcer Image
      run: |
        docker build --tag rpacheco26/docker-graphql:0.0.1 . 
        
    - name: Push Dokcer Image
      run: |
        docker push rpacheco26/docker-graphql:0.0.1
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
